pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/cgarvey00/scalable-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build & Push') {
            steps {
            script {
                docker.build('cgarvey2k25/scalable-app:latest')
                docker.withRegistry('https://index.docker.io/v1/','docker-hub-credentials'){
                sh 'docker push cgarvey2k25/scalable-app:latest'
               }
            }
        }
    }
         stage('Deploy'){
            steps{
                sh 'docker run -d --name scalable-app -p 3000:3000 cgarvey2k25/scalable-app:latest'
            }
         }
      }


    post {
        always {
            // Ensures the workspace is clear
            cleanWs()
        }
    }
}
